version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      all:
        patterns:
        - "*"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
